sudo: false
language: node_js
node_js:
  - 8
services:
  - postgresql
  - redis
script:
  - psql -c 'create database xmtest;' -U postgres
  - CLIENT_ID=$CLIENT_ID CLIENT_SECRET=$CLIENT_SECRET npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
